  mongoEndereco:
    image: mongo
    restart: always
    hostname: mongodb
    command: mongod --port 8082
    ports:
      - 8082:8082

  java8Endereco:
    image: shinyay/docker-mvn-jdk8:3.5.0
    ports:
    - "8087:8087"
    volumes:
    - ".:/usr/src/myapp"
    working_dir: /usr/src/myapp
    command: >
        bash -c "mvn install
        && cd target
        && java -jar endereco-0.0.1-SNAPSHOT.jar"
    links:
    - mongoEndereco
    
